version: 0.2
env:
  variables:
    SOLUTION: AmazonGameLiftPlugin.Core\AmazonGameLiftPlugin.Core.sln
    PACKAGE_DIRECTORY: AmazonGameLiftPlugin.Core\packages
    DOTNET_FRAMEWORK: 4.7
phases:
  build:
    commands:
      - echo Build started   
      - dir
      - choco install nuget.commandline --pre -y
      - '& nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& msbuild -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
      - dir
artifacts:
  files:
    - GameLift-Unity/Assets/**/*