{
 "title": "EC2 Fleet Overview",
 "description": "An overview of your GameLift Servers managed EC2 fleets",
 "tags": [
  "gamelift",
  "ec2",
  "fleet",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fleet_id",
    "label": "Fleet ID",
    "query": {
     "query": "label_values({deployment_type=\"EC2\"},fleet_id)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values({fleet_id=\"$fleet_id\"},cloud_region)"
    }
   },
   {
    "name": "instance_type",
    "label": "Instance Type",
    "query": {
     "query": "label_values({fleet_id=\"$fleet_id\"},host_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Instance Type:** <span style=\"text-transform: uppercase;\">${instance_type}</span>\n\nRelated dashboard: <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a>\n\n**Note:** This dashbord is only for managed EC2 fleets. See the <a href=\"/d/container_overview/container-overview\" target=\"_blank\">container fleet overview</a> dashboard for managed container fleets\n\nMonitor key fleet metrics for potential issues:\n\n- **Global CCU & Capacity** shows active player count and available game server processes globally for the fleet. Watch for capacity constraints and player distribution across regions.\n\n- **Location CCU** displays location-specific CCU. Identify regional issues and capacity balancing needs.\n\n- **Location Capacity** displays location-specific capacity in use (%). It is the average capacity in use across all the instances in the location.\n\nClick the information icon (ⓘ) next to each graph for detailed analysis and troubleshooting steps."
   }
  },
  {
   "title": "Global CCU and Capacity (All Locations)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CCU",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of concurrent users in all the game servers over all the instances in all locations.\n\n#### Why is it important?\n- Shows player distribution\n- Helps in capacity planning",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(server_players{fleet_id=\"$fleet_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(cloud_region) (server_players{fleet_id=\"$fleet_id\"})",
     "legendFormat": "{{cloud_region}}"
    }
   ]
  },
  {
   "title": "Global CCU",
   "type": "stat",
   "description": "#### What it means\nIt shows the number of concurrent users in all the game servers over all the instances in all locations globally.\n\n#### Why is it important?\n- Shows player distribution\n- Helps in capacity planning",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_players{fleet_id=\"$fleet_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Capacity Usage",
   "type": "gauge",
   "description": "#### What it means\nIt shows the capacity utilization (%) globally, and the percentage of game servers in-use globally.\n\n#### Why is it important?\n- Indicates there is a bottleneck for onboarding more game sessions\n\n#### What is the root cause?\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics for other instances. Sometimes, only a single instance is bad.\n\n#### How to mitigate the issue\n- Consider scaling the fleet to more numbers of instances in a location, and have a look at the \"Location capacity\" section to identify the locations with the highest usage.\n- Consider increasing the number of concurrent process in the runtime configuration of the fleet.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "aggregate" },
     "metricName": "ActiveGameSessions",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "aggregate" },
     "metricName": "ActiveServerProcesses",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Global Capacity Available (Game servers)",
   "type": "stat",
   "description": "#### What it means\nIt shows the total number of game servers in the fleet that are ready to receive a game session.\n\n#### Why is it important?\nIndicates a bottleneck for onboarding more game sessions.\n\n#### What is the root cause?\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics for other instances. Sometimes, only a single instance is bad.\n\n#### How to mitigate the issue\n- Consider scaling the fleet to more instances in a location, and have a look at \"Location capacity\" section to identify the locations with the highest usage.\n- Consider increasing the number of concurrent process in the runtime configuration of the fleet.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "aggregate" },
     "metricName": "ActiveServerProcesses",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "aggregate" },
     "metricName": "ActiveGameSessions",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "stat",
   "description": "#### What it means\nIt shows the total number of instances in the fleet that are active.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "ActiveInstances",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ActiveInstances", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "aggregate" }, "property": { "name": "Location", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ActiveInstances) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id' AND Location = 'aggregate'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Idle Instance %",
   "type": "gauge",
   "description": "#### What it means\nIt shows the average percentage of instances in the fleet (all locations) that do not have an active game session running.\n\n#### Why is it important?\nThis should be low in order to do effective cost savings.\n\n#### How to mitigate the issue\n- Identify the location that has idle capacity from the \"Location Capacity\" section.\n- Use auto-scaling policies as mentioned in the [guide](https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-autoscaling.html)\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "PercentIdleInstances", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(PercentIdleInstances) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Idle Instances",
   "type": "stat",
   "description": "#### What it means\nIt shows the number of instances in the fleet (all locations) that do not have an active game session running.\n\n#### Why is it important?\nThis should be low in order to do effective cost savings.\n\n#### How to mitigate the issue\n- Identify the location that has idle capacity from the \"Location Capacity\" section\n- Use auto-scaling policies as mentioned in the [guide](https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-autoscaling.html)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "ActiveInstances",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "IdleInstances", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(IdleInstances) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of active game server processes that are ready to host a game session.\n\n#### Why is it important?\nThis should be low in order to do effective cost savings.\n\n#### How to mitigate the issue\n- Identify the location that has idle capacity from the \"Location Capacity\" section\n- Use auto-scaling policies as mentioned in the [guide](https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-autoscaling.html)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "$location" },
     "metricName": "ActiveServerProcesses",
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Desired Instances",
   "type": "timeseries",
   "description": "#### What it means\nShows the number of instances in the fleet (all locations) that do not have an active game session running.\n\n#### Why is it important?\nThis should be low in order to do effective cost savings.\n\n#### How to mitigate the issue\n- Identify the location that has idle capacity from the \"Location Capacity\" section\n- Use auto-scaling policies as mentioned in the [guide](https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-autoscaling.html)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "$location" },
     "metricName": "DesiredInstances",
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Game Server Starts",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of game sessions that started across the fleet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "label": "ServerProcessActivations",
     "metricName": "DesiredInstances",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ServerProcessActivations", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ServerProcessActivations) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Game Server Stops",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of game sessions that stopped or crashed across the fleet.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "label": "ServerProcessTerminations",
     "metricName": "DesiredInstances",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ServerProcessTerminations", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ServerProcessTerminations) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Healthy Game Servers (%)",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the average percentage of game servers that report healthy to Amazon GameLift Servers across the fleet.\n\n#### Why is it important?\nIf the game servers are not healthy, no game sessions would be placed on them\n\n#### How to mitigate the issue\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics. For other instances, sometimes a only single instance is bad.\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "DesiredInstances",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Location", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "PercentHealthyServerProcesses", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(PercentHealthyServerProcesses) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id' GROUP BY Location",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Game Server Crashes",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of game servers that crashed across the fleet. \n\n#### Why is it important?\nA high number of game session crashes causes bad player experiences alongside resource waste and unwanted noise.\n\n#### How to mitigate the issue\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics. For other instances, sometimes a only single instance is bad.\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum by(fleet_id) (game_server_crash{fleet_id=\"$fleet_id\"})\nor (vector(0) * on() group_left(fleet_id) (label_replace(vector(1), \"fleet_id\", \"$fleet_id\", \"\", \"\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crashed Game Sessions",
   "type": "table",
   "description": "#### What it means\nIt shows the game session IDs of the crashed game sessions. Click the link of game session ARN to navigate to the Server Performance dashboard.\n\n#### Why is it important?\nA high number of game session crashes can cause bad player experiences along with resource waste and unwanted noise.\n\n#### How to mitigate the issue\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics. For other instances, sometimes a only single instance is bad.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "game_server_crash{fleet_id=\"$fleet_id\"}"
    }
   ]
  },
  { "title": "Location CCU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "$location",
   "type": "stat",
   "description": "#### What it means\nIt shows the number of concurrent users in a location, including all the game servers over all the instances in the location.\n\n#### Why is it important?\n- Shows player distribution\n- Helps in capacity planning",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "repeat": "location",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_players{cloud_region=\"$location\", fleet_id=\"$fleet_id\"})",
     "legendFormat": "$server_region"
    }
   ]
  },
  { "title": "Location Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "$location",
   "type": "timeseries",
   "description": "#### What it means\nIt shows capacity utilization (%) in a location, and the percentage of game servers in use in the location.\n\n#### Why is it important?\n- Indicates regional balance - in case we need to add more capacity to a specific location.\n- Indicates bottlenecks\n\n#### What is the root cause?\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances Overview</a> dashboard for instance metrics for other instances, sometimes a only single instance is bad.\n\n#### How to mitigate the issue\n- Consider scaling the fleet to more numbers of instances in the location.\n- Consider increasing the number of concurrent processes in the runtime configuration for the fleet.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "$location" },
     "metricName": "ActiveGameSessions",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FleetId": "$fleet_id", "Location": "$location" },
     "metricName": "ActiveServerProcesses",
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}