{
 "title": "Instance Performance",
 "tags": [
  "gamelift",
  "ec2",
  "instance",
  "performance"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(system_cpu_utilization_ratio{deployment_type=\"EC2\"},host_id)"
    }
   },
   {
    "name": "fleet_id",
    "label": "Fleet ID",
    "query": {
     "query": "label_values({host_id=\"$instance_id\"},fleet_id)"
    }
   },
   {
    "name": "instance_type",
    "label": "Instance Type",
    "query": {
     "query": "label_values({host_id=\"$instance_id\"},host_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard overview",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Fleet ID:** <a href=\"/d/fleet_overview/fleet-overview?var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">${fleet_id}</a><br>\n**Instance Type:** </span> <span style=\"text-transform: uppercase;\">${instance_type}</span>\n\nRelated dashboards: <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a> | <a href=\"/d/fleet_overview/fleet-overview?var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">EC2 fleet overview</a>\n\n**Note:** This dashboard is only for EC2 fleets, for container fleets see the <a href=\"/d/container_performance/container-performance\" target=\"_blank\">container performance</a> dashboard\n\nMonitor each metric type for potential issues:\n\n- **Current Averages** shows overall instance health. When performance degrades, check CPU usage, memory consumption, and file system consumption for bottlenecks.\n\n- **Load Summary** tracks resource usage by game servers. High utilization patterns require checking induvidual session metrics and resource distribution like CPU and memory.\n\n- **Network** reflects instance connectivity. For latency or connectivity issues, investigate Network I/O, Packet rates, and Error counts.\n\n- **Disk** indicates disk performance. Slow response times suggest examining Disk operations, I/O wait times, and Pending operations.\n\nClick the information icon (ⓘ) next to each graph for detailed analysis and troubleshooting steps."
   }
  },
  { "title": "Current averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "#### What it means\nReal-time gauges show overall processor utilization across all cores.\n\n#### Why is it important?\nIt's critical for identifying immediate resource constraints that affect game server performance.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host_id) (1 - rate(system_cpu_time_seconds_total{host_id=\"$instance_id\", state=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "#### What it means\nReal-time gauges showing total RAM consumption percentage.\n\n#### Why is it important?\nIt's critical for identifying immediate resource constraints affecting game server performance.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{host_id=\"$instance_id\", state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "gauge",
   "description": "#### What it means\nReal-time gauges showing root partition storage utilization.\n\n#### Why is it important?\nIt's critical for identifying immediate resource constraints affecting game server performance.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_utilization_ratio{host_id=\"$instance_id\", mountpoint=~\"/|C:\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "#### What it means\nDetailed breakdown of memory usage by type:\n- `used`: Actually used memory\n- `cached`: File system cache\n- `buffers`: System buffers\n\n#### Why is it important?\n- Shows memory pressure trends\n- Helps identify memory leaks\n- Reveals caching behavior\n\n#### How to identify the root cause\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n- Check if it is across all instances or specific to this instance only. You can refer to the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a> dashboard.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance.\n- Adjust the instance type of the fleet.\n- Make changes to optimize game server code for memory. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_id=\"$instance_id\", state!=\"free\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top 10 Memory Consuming Game Sessions",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(\r\n  process_memory_usage_bytes{host_id=\"${instance_id}\",process_owner=~\".*gl-user-server\"}\r\n  * on (process_pid) group_left (session_id)\r\n  (server_up{host_id=\"${instance_id}\",session_id=~\".+\"})\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "#### What it means\nIt shows CPU time broken down by different usage types:\n- `user`: Time spent running user-space processes (game server application)\n- `system`: Time spent executing kernel-level operations\n- `wait`: Time spent waiting for I/O operations (disk, network)\n- `interrupt`: Time spent handling hardware interrupts\n- `softirq`: Time spent handling software interrupts (networking, scheduling)\n- `nice`: Time spent running user processes with modified priority\n- `steal`: Time that the CPU was requested but not received (virtual environments)\n\n#### Why is it important?\n- High `user` time suggests compute-intensive game logic\n- High `system` time indicates heavy kernel operations\n- High `wait` time shows I/O bottlenecks\n- High `interrupt`/`softirq` suggests network or hardware stress\n- High `steal` time indicates VM resource contention\n\n#### How to identify the root cause\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n- Check if it is across all instances or this instance specifically. You can refer to the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a> dashboard.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance.\n- Adjust the instance type of the fleet.\n- Make changes to optimize game server code.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(state) (system_cpu_utilization_ratio{state!=\"idle\", host_id=\"$instance_id\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top 10 CPU Consuming Game Sessions",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  rate(process_cpu_time_seconds_total{\n    process_owner=~\".*gl-user-server\",\n    state=\"user\",\n    host_id=\"${instance_id}\"\n  }[1m]) \n  * on (process_pid) group_left(session_id)\n  (\n    server_up{\n      host_id=\"${instance_id}\", \n      session_id=~\".+\"\n    }\n  )\n) * 100 / on() group_left() count(\n  system_cpu_utilization_ratio{state=\"idle\", host_id=\"${instance_id}\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m{host_id=\"$instance_id\"}",
     "legendFormat": "1 minute"
    },
    {
     "expr": "system_cpu_load_average_5m{host_id=\"$instance_id\"}",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "system_cpu_load_average_15m{host_id=\"$instance_id\"}",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{host_id=\"$instance_id\", mountpoint=~\"/|C:\", state!=\"free\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network Bytes I/O",
   "type": "timeseries",
   "description": "#### What it means\nComprehensive network performance metrics:\n- Bytes I/O: Data transfer volume\n- Transmit and receive data for each of the network interfaces on the instance\n\n#### Why is it important?\n- Monitors network health\n- Identifies connectivity issues\n- Helps diagnose latency problems\n\n#### How to identify the root cause\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check whether it is across all instances or this instance only. You can refer to the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a> dashboard.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance.\n- Adjust the instance type of the fleet.\n- Make changes to optimize game server code.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{direction}} ({{device}})"
    }
   ]
  },
  {
   "title": "Network Packets I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(system_network_packets_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{direction}} ({{device}})"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(system_network_errors_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{direction}} ({{device}})"
    }
   ]
  },
  {
   "title": "Network Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(system_network_dropped_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{direction}} ({{device}})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "system_network_connections{host_id=\"$instance_id\"}",
     "legendFormat": "{{protocol}} {{state}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Disk Operations I/O",
   "type": "timeseries",
   "description": "#### What it means\nDisk performance metrics:\n- Operations I/O: Read/write operations per second\n- Bytes I/O: Data transfer volume\n- Operation Time: Time spent on disk operations\n- I/O Time: Total time disk is busy\n- Pending Operations: Queued disk operations\n\n#### Why is it important?\n- Identifies disk bottlenecks\n- Monitors storage performance\n- Helps optimize I/O patterns\n\n#### How to identify the root cause\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check if it is across all instances or this instance only. You can refer to the <a href=\"/d/instance_overview/instances-overview?var-instance_type=All&var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">Instances overview</a> dashboard.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance.\n- Adjust the instance type of the fleet.\n- Make changes to optimize the game server code.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(system_disk_operations_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Disk Bytes I/O",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Disk Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_disk_operation_time_seconds_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}: {{direction}}"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_time_seconds_total{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Pending Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(system_disk_pending_operations{host_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Game Server Crashes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Game Server Crashes",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the number of game servers that crashed across the EC2 instance. \n\n#### Why is it important?\nA high number of game session crashes causes bad player experiences alongside resource waste and unwanted noise.\n\n#### How to mitigate the issue\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/server_performance_ec2/ec2-server-performance?from=${__from}&to=${__to}\" target=\"_blank\">EC2 Server Performance Overview</a> dashboard for Game Server metrics.\n\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum by(fleet_id) (game_server_crash{fleet_id=\"$fleet_id\", host_id=\"$instance_id\"})\nor (vector(0) * on() group_left(fleet_id) (label_replace(vector(1), \"fleet_id\", \"$fleet_id\", \"\", \"\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crashed Game Sessions",
   "type": "table",
   "description": "#### What it means\nIt shows the game session IDs of the crashed game sessions. Click the link of game session ARN to navigate to the Server Performance dashboard.\n\n#### Why is it important?\nA high number of game session crashes can cause bad player experiences along with resource waste and unwanted noise.\n\n#### How to mitigate the issue\n- Often, the game servers crash prematurely. Proactively check for the number of crashed game sessions and review the game server logs for the reason.\n- Check the <a href=\"/d/server_performance_ec2/ec2-server-performance?from=${__from}&to=${__to}\" target=\"_blank\">EC2 Server Performance Overview</a> dashboard for Game Server metrics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "game_server_crash{fleet_id=\"$fleet_id\",host_id=\"$instance_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}