{
 "title": "Instances Overview",
 "tags": [
  "gamelift",
  "ec2",
  "instance",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance_type", "label": "Instance Type", "query": { "query": "label_values(host_type)" } },
   {
    "name": "fleet_id",
    "label": "Fleet ID",
    "query": {
     "query": "label_values({host_type=~\"$instance_type\", deployment_type=\"EC2\"},fleet_id)"
    }
   },
   {
    "name": "instance_type_of_fleet",
    "label": "Instance Type of Fleet (read only)",
    "query": {
     "query": "label_values({fleet_id=\"$fleet_id\"},host_type)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values({fleet_id=\"$fleet_id\"},cloud_region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard overview",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Fleet ID:** <a href=\"/d/fleet_overview/fleet-overview?var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">${fleet_id}</a><br>\n**Instance Type:** </span> <span style=\"text-transform: uppercase;\">${instance_type_of_fleet}</span>\n\nRelated dashboards: <a href=\"/d/fleet_overview/fleet-overview?var-fleet_id=${fleet_id}&from=${__from}&to=${__to}\" target=\"_blank\">EC2 fleet overview</a>\n\n**Note:** This dashboard is only for EC2 fleets, for container fleets see the <a href=\"/d/container_overview/container-overview\" target=\"_blank\">container fleet overview</a> dashboard\n\nMonitor each metric type for potential issues:\n\n- **Current averages** shows overall health of the instances. When performance degrades, check CPU usage, memory consumption, network and disk consumption for bottlenecks.\n\n- **Instance summary** tracks average resource usage by instances. High utilization patterns require checking induvidual instance metrics and resource distribution like CPU and memory.\n\n- **Network summary** reflects average instance connectivity. For latency or connectivity issues, check induvidual instance metrics like Network I/O and Packet rates.\n\n- **Disk summary** indicates average disk performance of the instances. Slow response times suggest examining Disk operations, I/O wait times, and Pending operations at the induvidual instance level.\n\nClick the information icon (ⓘ) next to each graph for detailed analysis and troubleshooting steps."
   }
  },
  { "title": "Current averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "#### What it means\nReal-time gauges show average processor utilization across all instances.\n\n#### Why is it important?\nIt's critical for identifying immediate resource constraints that affect game server performance.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "metricQueryType": 1,
     "namespace": "AWS/GameLift",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/GameLift", "type": "functionParameter" },
        { "name": "FleetId", "type": "functionParameter" },
        { "name": "Location", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fleet_id" }, "property": { "name": "FleetId", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "aggregate" }, "property": { "name": "Location", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id' AND Location = 'aggregate'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network in",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of incoming network traffic across all instances.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(NetworkIn) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network out",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of outgoing network traffic across all instances.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(NetworkOut) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk read ops",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of disk read operations across all instances.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(DiskReadOps) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of disk read bytes across all instances.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sqlExpression": "SELECT AVG(DiskReadBytes) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk write ops",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of disk write operations across all instances.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(DiskWriteOps) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "stat",
   "description": "#### What it means\nIt shows the average rate of disk write bytes across all instances.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sqlExpression": "SELECT AVG(DiskWriteBytes) FROM SCHEMA(\"AWS/GameLift\", FleetId, Location) WHERE FleetId = '$fleet_id'",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Instance summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the average processor utilization across all instances.\n\n#### Why is it important?\nIt impacts player experience and server tick rate.\n\n#### How to identify the root cause\n- Investigate if a specific instance is resulting in a high average with the help of the table beside it.\n- Check if it is caused by a specific game session or all game sessions by checking the instance performance graph.\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n\n#### How to mitigate the issue\n- Adjust the number of instances in the location.\n- Adjust the number of concurrent game servers running on the instance.\n- Create a new fleet with a different instance type.\n- Make changes to optimize the game server code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(\n  avg by (host_id) ( # Step 2: Average across hosts\n    avg by (host_id) ( # Step 1: Average across CPUs per host\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n  )\n))",
     "legendFormat": "Mean"
    },
    {
     "expr": "100 * (1 - min(\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n))",
     "legendFormat": "Max"
    },
    {
     "expr": "100 * (1 - max(\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n))",
     "legendFormat": "Min"
    },
    {
     "expr": "100 * (1 - quantile(0.01,\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n))",
     "legendFormat": "P99"
    },
    {
     "expr": "100 * (1 - quantile(0.05,\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n))",
     "legendFormat": "P95"
    },
    {
     "expr": "100 * (1 - quantile(0.10,\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by CPU consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (host_id) (\n    avg by (host_id) (\n      rate(system_cpu_time_seconds_total{\n        state=\"idle\",\n        cloud_region=~\"${location:regex}\",\n        fleet_id=\"$fleet_id\"\n      }[$__rate_interval])\n    )\n  )\n)\n\n\n\n\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the average memory utilization across all instances.\n\n#### Why is it important?\nImpacts player experience and critical for identifying immediate resource constraints affecting game server performance\n\n#### How to identify the root cause\n- Investigate if a specific instance is resulting in a high average with the help of the table beside.\n- Check if it is caused by a specific game session or all game sessions by checking the instance performance graph.\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n\n#### How to mitigate the issue\n- Adjust the number of instances in the location.\n- Adjust the number of concurrent game servers running on the instance.\n- Create a new fleet with a different instance type.\n- Make changes to optimize game server code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    system_memory_usage_bytes{\n      state=\"used\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by memory consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  system_memory_usage_bytes{\n    state=\"used\",\n    cloud_region=~\"${location:regex}\",\n    fleet_id=\"$fleet_id\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network in",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the average rate of incoming network traffic across all instances.\n\n#### Why is it important?\n- Monitors network health\n- Identifies connectivity issues\n- Helps diagnose latency problems\n\n#### How to identify the root cause\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n- Refer to the table beside it and check the instance performance graphs.\n- Check if it is caused by a specific game session or all game sessions on the specific instance.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"receive\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Network In consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_network_io_bytes_total{\n    host_id=~\".*\",\n    cloud_region=~\"${location:regex}\",\n    direction=\"receive\",\n    device=~\".*\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network out",
   "type": "timeseries",
   "description": "#### What it means\nIt shows the average rate of outgoing network traffic across all instances.\n\n#### Why is it important?\n- Monitors network health\n- Identifies connectivity issues\n- Helps diagnose latency problems\n\n#### How to identify the root cause\n- Investigate the game session graphs to figure out if the game server build is causing problems.\n- Refer to the table it beside and check the instance performance graphs.\n- Check if it is caused by a specific game session or all game sessions on the specific instance.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_network_io_bytes_total{\n      host_id=~\".*\",\n      cloud_region=~\"${location:regex}\",\n      direction=\"transmit\",\n      device=~\".*\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Network Out consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_network_io_bytes_total{\n    host_id=~\".*\",\n    cloud_region=~\"${location:regex}\",\n    direction=\"transmit\",\n    device=~\".*\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Disk write bytes",
   "type": "timeseries",
   "description": "#### What it means\nDisk performance metrics:\n- Operations I/O: Read/write operations per second\n- Bytes I/O: Data transfer volume\n- Operation Time: Time spent on disk operations\n\n#### Why is it important?\n- Identifies disk bottlenecks\n- Monitors storage performance\n- Helps optimize I/O patterns\n\n#### How to identify the root cause\n- Check if it is across all instances or this instance only. You can refer to the table beside it to determine this. You may then navigate to the instance's performance graph to dive deeper.\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize the game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"write\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Disk Write",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_disk_io_bytes_total{\n    direction=\"write\",\n    cloud_region=~\"${location:regex}\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk write ops",
   "type": "timeseries",
   "description": "#### What it means\nDisk performance metrics:\n- Operations I/O: Read/write operations per second\n- Bytes I/O: Data transfer volume\n- Operation Time: Time spent on disk operations\n\n#### Why is it important?\n- Identifies disk bottlenecks\n- Monitors storage performance\n- Helps optimize I/O patterns\n\n#### How to identify the root cause\n- Check if it is across all instances or this instance only. You can refer to the table beside it to determine this. You may then navigate to the instance's performance graph to dive deeper.\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize the game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"write\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Disk Write operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_disk_operations_total{\n    direction=\"write\", \n    cloud_region=~\"${location:regex}\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "timeseries",
   "description": "#### What it means\nDisk performance metrics:\n- Operations I/O: Read/write operations per second\n- Bytes I/O: Data transfer volume\n- Operation Time: Time spent on disk operations\n\n#### Why is it important?\n- Identifies disk bottlenecks\n- Monitors storage performance\n- Helps optimize I/O patterns\n\n#### How to identify the root cause\n- Check if it is across all instances or this instance only. You can refer to the table beside it to determine this. You may then navigate to the instance's performance graph to dive deeper.\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize the game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_disk_io_bytes_total{\n      direction=\"read\",\n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Disk Read",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_disk_io_bytes_total{\n    direction=\"read\",\n    cloud_region=~\"${location:regex}\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read ops",
   "type": "timeseries",
   "description": "#### What it means\nDisk performance metrics:\n- Operations I/O: Read/write operations per second\n- Bytes I/O: Data transfer volume\n- Operation Time: Time spent on disk operations\n\n#### Why is it important?\n- Identifies disk bottlenecks\n- Monitors storage performance\n- Helps optimize I/O patterns\n\n#### How to identify the root cause\n- Check if it is across all instances or this instance only. You can refer to the table beside it to determine this. You may then navigate to the instance's performance graph to dive deeper.\n- Investigate game session graphs to figure out if the game server build is causing problems.\n- Check if it is caused by a specific game session or all game sessions.\n\n#### How to mitigate the issue\n- Adjust the number of concurrent game servers running on the instance\n- Adjust the instance type of the fleet\n- Make changes to optimize the game server code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "max(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)\n",
     "legendFormat": "Min"
    },
    {
     "expr": "quantile(0.99,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile(0.95,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.90,\n  sum by (host_id) (\n    rate(system_disk_operations_total{\n      direction=\"read\", \n      cloud_region=~\"${location:regex}\",\n      fleet_id=\"$fleet_id\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Top 20 EC2 instances by Disk Read operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (host_id) (\n  rate(system_disk_operations_total{\n    direction=\"read\", \n    cloud_region=~\"${location:regex}\",\n    fleet_id=\"$fleet_id\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}